# Implementation of arrays in python

In [1]:
A=[[1, 2, 3, 4], [2, 3, 6, 8]]

# Rise of numpy

In [2]:
import numpy as np

## np matrices

In [3]:
np.matrix([[1, 2, 3, 4], [2, 3, 6, 8]])

matrix([[1, 2, 3, 4],
        [2, 3, 6, 8]])

## np arrays

In [4]:
np.array([2, 3, 6, 8])

array([2, 3, 6, 8])

## arrays vs. matrices

In [5]:
np.matrix([2, 3, 6, 8]), np.array([2, 3, 6, 8])

(matrix([[2, 3, 6, 8]]), array([2, 3, 6, 8]))

## Let's play

In [6]:
np.zeros((2, 3, 4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [7]:
np.ones((2, 3, 4))

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [8]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

## Slicing

In [9]:
A=np.array([[[1, 2, 3, 4], 
             [2, 3, 6, 8]], 
            [[10, 20, 30, 40], 
             [20, 30, 60, 80]]])
A

array([[[ 1,  2,  3,  4],
        [ 2,  3,  6,  8]],

       [[10, 20, 30, 40],
        [20, 30, 60, 80]]])

In [10]:
A.ndim

3

In [11]:
A.shape

(2, 2, 4)

In [12]:
A[1]

array([[10, 20, 30, 40],
       [20, 30, 60, 80]])

In [13]:
A[1,:,:]

array([[10, 20, 30, 40],
       [20, 30, 60, 80]])

In [14]:
A[:,1,:]

array([[ 2,  3,  6,  8],
       [20, 30, 60, 80]])

In [15]:
A[:,1,1]

array([ 3, 30])

In [16]:
A[1,1,1]

30

In [17]:
A[:,:,1:3]

array([[[ 2,  3],
        [ 3,  6]],

       [[20, 30],
        [30, 60]]])

## Reshape

In [18]:
A = np.arange(10, 100)
A

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60,
       61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77,
       78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94,
       95, 96, 97, 98, 99])

In [19]:
A.shape

(90,)

In [20]:
A = A.reshape(2, 5, 3, 3)
A.shape

(2, 5, 3, 3)

In [21]:
A

array([[[[10, 11, 12],
         [13, 14, 15],
         [16, 17, 18]],

        [[19, 20, 21],
         [22, 23, 24],
         [25, 26, 27]],

        [[28, 29, 30],
         [31, 32, 33],
         [34, 35, 36]],

        [[37, 38, 39],
         [40, 41, 42],
         [43, 44, 45]],

        [[46, 47, 48],
         [49, 50, 51],
         [52, 53, 54]]],


       [[[55, 56, 57],
         [58, 59, 60],
         [61, 62, 63]],

        [[64, 65, 66],
         [67, 68, 69],
         [70, 71, 72]],

        [[73, 74, 75],
         [76, 77, 78],
         [79, 80, 81]],

        [[82, 83, 84],
         [85, 86, 87],
         [88, 89, 90]],

        [[91, 92, 93],
         [94, 95, 96],
         [97, 98, 99]]]])

## Slicing (2)

In [23]:
A = np.arange(10, 20)
A

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [24]:
A[[3, 7, 7, 7]]

array([13, 17, 17, 17])

In [25]:
A = np.arange(0, 24).reshape(3, 2, 4)
A

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]],

       [[16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [26]:
B = A[[0, 2, 1, 1], :, :]
B

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[16, 17, 18, 19],
        [20, 21, 22, 23]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

## transposition

In [27]:
A.shape

(3, 2, 4)

In [28]:
A.transpose((0, 2, 1))

array([[[ 0,  4],
        [ 1,  5],
        [ 2,  6],
        [ 3,  7]],

       [[ 8, 12],
        [ 9, 13],
        [10, 14],
        [11, 15]],

       [[16, 20],
        [17, 21],
        [18, 22],
        [19, 23]]])

In [29]:
A.transpose((0, 2, 1)).shape

(3, 4, 2)

In [30]:
A.transpose((1, 2, 0))

array([[[ 0,  8, 16],
        [ 1,  9, 17],
        [ 2, 10, 18],
        [ 3, 11, 19]],

       [[ 4, 12, 20],
        [ 5, 13, 21],
        [ 6, 14, 22],
        [ 7, 15, 23]]])

In [31]:
A.transpose((1, 2, 0)).shape

(2, 4, 3)