# Data Preparation

## Load Data

In [14]:
import pandas as pd

table = pd.read_excel('ToyotaCorolla.xls', sheetname='data')

In [15]:
table.columns

Index([u'Id', u'Model', u'Price', u'Age_08_04', u'Mfg_Month', u'Mfg_Year',
       u'KM', u'Fuel_Type', u'HP', u'Met_Color', u'Color', u'Automatic', u'CC',
       u'Doors', u'Cylinders', u'Gears', u'Quarterly_Tax', u'Weight',
       u'Mfr_Guarantee', u'BOVAG_Guarantee', u'Guarantee_Period', u'ABS',
       u'Airbag_1', u'Airbag_2', u'Airco', u'Automatic_airco',
       u'Boardcomputer', u'CD_Player', u'Central_Lock', u'Powered_Windows',
       u'Power_Steering', u'Radio', u'Mistlamps', u'Sport_Model',
       u'Backseat_Divider', u'Metallic_Rim', u'Radio_cassette',
       u'Parking_Assistant', u'Tow_Bar'],
      dtype='object')

`Fuel_Type` and `Color` are not numeric variabled.

## Categorical to Numerical Conversion

In [16]:
print("Fuel_Type valuies: ", set(table['Fuel_Type']))
print("Color valuies: ", set(table['Color']))

('Fuel_Type valuies: ', set([u'Petrol', u'CNG', u'Diesel']))
('Color valuies: ', set([u'Blue', u'Grey', u'Yellow', u'Black', u'Beige', u'Violet', u'Green', u'White', u'Silver', u'Red']))


In [17]:
data = table[['Id', 'Model', 'Price', 'Age_08_04', 'Mfg_Month', 'Mfg_Year', 'KM',
       'HP', 'Met_Color', 'Automatic', 'CC', 'Doors',
       'Cylinders', 'Gears', 'Quarterly_Tax', 'Weight', 'Mfr_Guarantee',
       'BOVAG_Guarantee', 'Guarantee_Period', 'ABS', 'Airbag_1', 'Airbag_2',
       'Airco', 'Automatic_airco', 'Boardcomputer', 'CD_Player',
       'Central_Lock', 'Powered_Windows', 'Power_Steering', 'Radio',
       'Mistlamps', 'Sport_Model', 'Backseat_Divider', 'Metallic_Rim',
       'Radio_cassette', 'Parking_Assistant', 'Tow_Bar']].copy()

In [18]:
data['Diesel'] = (table['Fuel_Type'] == 'Diesel') * 1
data['Petrol'] = (table['Fuel_Type'] == 'Petrol') * 1

In [19]:
for color_name in list(set(table['Color']))[1:]:
    data[color_name] = (table['Color'] == color_name) * 1    

In [20]:
table = data.copy()

In [21]:
table.columns

Index([               u'Id',             u'Model',             u'Price',
               u'Age_08_04',         u'Mfg_Month',          u'Mfg_Year',
                      u'KM',                u'HP',         u'Met_Color',
               u'Automatic',                u'CC',             u'Doors',
               u'Cylinders',             u'Gears',     u'Quarterly_Tax',
                  u'Weight',     u'Mfr_Guarantee',   u'BOVAG_Guarantee',
        u'Guarantee_Period',               u'ABS',          u'Airbag_1',
                u'Airbag_2',             u'Airco',   u'Automatic_airco',
           u'Boardcomputer',         u'CD_Player',      u'Central_Lock',
         u'Powered_Windows',    u'Power_Steering',             u'Radio',
               u'Mistlamps',       u'Sport_Model',  u'Backseat_Divider',
            u'Metallic_Rim',    u'Radio_cassette', u'Parking_Assistant',
                 u'Tow_Bar',            u'Diesel',            u'Petrol',
                    u'Grey',            u'Yellow', 

In [22]:
table.to_excel('ToyotaCorolla_cat2num.xls', sheet_name='data')

## Set Input and Output

In [13]:
print(table)

        Id                                              Model  Price  \
0        1      TOYOTA Corolla 2.0 D4D HATCHB TERRA 2/3-Doors  13500   
1        2      TOYOTA Corolla 2.0 D4D HATCHB TERRA 2/3-Doors  13750   
2        3      TOYOTA Corolla 2.0 D4D HATCHB TERRA 2/3-Doors  13950   
3        4      TOYOTA Corolla 2.0 D4D HATCHB TERRA 2/3-Doors  14950   
4        5        TOYOTA Corolla 2.0 D4D HATCHB SOL 2/3-Doors  13750   
5        6        TOYOTA Corolla 2.0 D4D HATCHB SOL 2/3-Doors  12950   
6        7      TOYOTA Corolla 2.0 D4D 90 3DR TERRA 2/3-Doors  16900   
7        8      TOYOTA Corolla 2.0 D4D 90 3DR TERRA 2/3-Doors  18600   
8        9        TOYOTA Corolla 1800 T SPORT VVT I 2/3-Doors  21500   
9       10        TOYOTA Corolla 1.9 D HATCHB TERRA 2/3-Doors  12950   
10      11  TOYOTA Corolla 1.8 VVTL-i T-Sport 3-Drs 2/3-Doors  20950   
11      12  TOYOTA Corolla 1.8 16V VVTLI 3DR T SPORT BNS 2...  19950   
12      13  TOYOTA Corolla 1.8 16V VVTLI 3DR T SPORT 2/3-D...  1

In [12]:
X = table[['Age_08_04', 'Mfg_Month', 'Mfg_Year', 'KM',
       'HP', 'Met_Color', 'Automatic', 'CC', 'Doors', 'Cylinders', 'Gears',
       'Quarterly_Tax', 'Weight', 'Mfr_Guarantee', 'BOVAG_Guarantee',
       'Guarantee_Period', 'ABS', 'Airbag_1', 'Airbag_2', 'Airco',
       'Automatic_airco', 'Boardcomputer', 'CD_Player', 'Central_Lock',
       'Powered_Windows', 'Power_Steering', 'Radio', 'Mistlamps',
       'Sport_Model', 'Backseat_Divider', 'Metallic_Rim', 'Radio_cassette',
       'Parking_Assistant', 'Tow_Bar', 'Diesel', 'Petrol', 'Silver',
       'Violet', 'Grey', 'Yellow', 'Beige', 'Green', 'Red', 'Black',
       'White']]
y = table['Price']

X = X.as_matrix()
y = y.as_matrix()

In [13]:
import numpy as np

#Shuffle data
permutation = np.random.permutation(len(X))
X = X[permutation]
y = y[permutation]

# Split data
N_train = int(len(X) * 4 / 5)

X_train = X[:N_train]
y_train = y[:N_train]

X_test = X[N_train:]
y_test = y[N_train:]

# Linear Regression Using Scikit-Learn

In [14]:
from sklearn import linear_model

lm = linear_model.LinearRegression()
model = lm.fit(X_train,y_train)

In [15]:
model.coef_

array([-1.15405782e+02, -9.28749401e+01,  1.73567268e+01, -1.62204228e-02,
        1.77905202e+01, -4.07448387e+01,  3.82897434e+02, -9.32081547e-02,
        6.48687661e+01,  5.68434189e-14,  8.14203246e+01,  1.34293924e+01,
        9.71689374e+00,  2.86105713e+02,  3.59867454e+02,  6.62694851e+01,
       -2.05100423e+02, -1.09684559e+01, -1.24881056e+02,  2.41972809e+02,
        2.58338007e+03, -2.30685498e+02,  1.89972240e+02, -7.47198388e+01,
        3.43924971e+02,  1.79530311e+02,  5.28408813e+02, -2.64369587e+01,
        3.42282584e+02, -2.29558656e+02,  1.91395648e+02, -5.93893178e+02,
       -7.04089329e+02, -2.11983466e+02,  4.84519032e+01,  1.03843543e+03,
       -1.08688734e+03,  2.73759411e+02, -2.10591766e+02,  3.53725278e+02,
       -1.77782279e+02, -1.41983098e+02, -1.06984592e+02,  9.98291065e+01,
        2.27663115e+02,  2.46591977e+02, -5.64227152e+02])

## Evaluation

In [16]:
y_train_hat = model.predict(X_train)
y_test_hat = model.predict(X_test)

In [17]:
print(np.round(y_train[:10]))
print(np.round(y_train_hat[:10]))

[22500  9895  8750  9500  8250 10950 11500 21950 10750  5950]
[20808.  9063.  7298. 10914.  9040. 10971. 11446. 20367. 11623.  6928.]


In [18]:
print(np.round(y_test[:10]))
print(np.round(y_test_hat[:10]))

[ 9450  9750  9500 18950  7950 15950  6950 11450  7200  8500]
[ 9877.  9926.  7974. 19472.  8506. 16901.  6132. 12943.  7073.  8166.]


In [19]:
from sklearn import metrics

print("Train r^2: ", metrics.r2_score(y_train, y_train_hat))
print("Test r^2: ", metrics.r2_score(y_test, y_test_hat))

Train r^2:  0.9107571206082735
Test r^2:  0.9078512159417295


# Regularization

In [20]:
from sklearn import linear_model

lm = linear_model.Lasso(alpha=0.1, max_iter=10000)
model = lm.fit(X_train,y_train)

In [21]:
y_train_hat = model.predict(X_train)
y_test_hat = model.predict(X_test)

In [22]:
from sklearn import metrics

print("Train r^2: ", metrics.r2_score(y_train, y_train_hat))
print("Test r^2: ", metrics.r2_score(y_test, y_test_hat))

Train r^2:  0.9107541091112991
Test r^2:  0.9078513330509672
