In [6]:
a=[1,2,3,"salam" , 5]

In [7]:
a[3]

'salam'

In [9]:
for item in a:
print item

IndentationError: expected an indented block (<ipython-input-9-2bb931319a8f>, line 2)

In [15]:
a=[10,20,3,15,1000,60,16]

a[1:4]

In [30]:
import numpy as np


In [31]:
a=np.matrix([[1,2,3,4],[2,3,6,8]])

In [32]:
np.matrix([1,2,3,4]) ,np.array([1,2,3,4]) 

(matrix([[1, 2, 3, 4]]), array([1, 2, 3, 4]))

a.ndim

In [33]:
a.shape

(2, 4)

In [35]:
np.zeros((2,3,4))

array([[[ 0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.]],

       [[ 0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.]]])

In [36]:
np.ones((2,3,4))

array([[[ 1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.]],

       [[ 1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.]]])

In [39]:
np.eye(5)

array([[ 1.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  1.]])

In [41]:
A=np.array([[1,2,3,4],[2,3,6,8]])
A

array([[1, 2, 3, 4],
       [2, 3, 6, 8]])

In [44]:
A=np.Transpose()
A

AttributeError: 'module' object has no attribute 'Transpose'

In [53]:
A=np.arange(10,100)

In [48]:
A.shape

(90,)

In [58]:
A=A.reshape(10,9)
A.shape

(10, 9)

In [57]:
A[1].shape

()

In [59]:
A=np.arange(0,75).reshape(3,5,5)

In [60]:
A

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24]],

       [[25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49]],

       [[50, 51, 52, 53, 54],
        [55, 56, 57, 58, 59],
        [60, 61, 62, 63, 64],
        [65, 66, 67, 68, 69],
        [70, 71, 72, 73, 74]]])

In [63]:
A.Transpose((1,2,0)).shape

AttributeError: 'numpy.ndarray' object has no attribute 'Transpose'

In [65]:
A=np.arange(10,20)
A

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [66]:
A[1:4]

array([11, 12, 13])

In [69]:
A[[3,7]]

array([13, 17])

In [70]:
X=A.copy()
X[1]=200000

In [71]:
X[1]

200000