# Data Preparation

## Load Data

In [1]:
import pandas as pd

table = pd.read_excel('./data/ToyotaCorolla.xls', sheet_name='data')

In [2]:
table.columns

Index(['Id', 'Model', 'Price', 'Age_08_04', 'Mfg_Month', 'Mfg_Year', 'KM',
       'Fuel_Type', 'HP', 'Met_Color', 'Color', 'Automatic', 'CC', 'Doors',
       'Cylinders', 'Gears', 'Quarterly_Tax', 'Weight', 'Mfr_Guarantee',
       'BOVAG_Guarantee', 'Guarantee_Period', 'ABS', 'Airbag_1', 'Airbag_2',
       'Airco', 'Automatic_airco', 'Boardcomputer', 'CD_Player',
       'Central_Lock', 'Powered_Windows', 'Power_Steering', 'Radio',
       'Mistlamps', 'Sport_Model', 'Backseat_Divider', 'Metallic_Rim',
       'Radio_cassette', 'Parking_Assistant', 'Tow_Bar'],
      dtype='object')

`Fuel_Type` and `Color` are not numeric variabled.

## Categorical to Numerical Conversion

In [3]:
print("Fuel_Type valuies: ", set(table['Fuel_Type']))
print("Color valuies: ", set(table['Color']))

Fuel_Type valuies:  {'Diesel', 'Petrol', 'CNG'}
Color valuies:  {'Blue', 'Grey', 'Black', 'Red', 'Violet', 'Beige', 'White', 'Yellow', 'Green', 'Silver'}


In [4]:
data = table[['Id', 'Model', 'Price', 'Age_08_04', 'Mfg_Month', 'Mfg_Year', 'KM',
       'HP', 'Met_Color', 'Automatic', 'CC', 'Doors',
       'Cylinders', 'Gears', 'Quarterly_Tax', 'Weight', 'Mfr_Guarantee',
       'BOVAG_Guarantee', 'Guarantee_Period', 'ABS', 'Airbag_1', 'Airbag_2',
       'Airco', 'Automatic_airco', 'Boardcomputer', 'CD_Player',
       'Central_Lock', 'Powered_Windows', 'Power_Steering', 'Radio',
       'Mistlamps', 'Sport_Model', 'Backseat_Divider', 'Metallic_Rim',
       'Radio_cassette', 'Parking_Assistant', 'Tow_Bar']].copy()

In [5]:
data['Diesel'] = (table['Fuel_Type'] == 'Diesel') * 1
data['Petrol'] = (table['Fuel_Type'] == 'Petrol') * 1

In [6]:
for color_name in sorted(list(set(table['Color'])))[1:]:
    data[color_name] = (table['Color'] == color_name) * 1    

In [7]:
table = data.copy()

In [8]:
table.columns

Index(['Id', 'Model', 'Price', 'Age_08_04', 'Mfg_Month', 'Mfg_Year', 'KM',
       'HP', 'Met_Color', 'Automatic', 'CC', 'Doors', 'Cylinders', 'Gears',
       'Quarterly_Tax', 'Weight', 'Mfr_Guarantee', 'BOVAG_Guarantee',
       'Guarantee_Period', 'ABS', 'Airbag_1', 'Airbag_2', 'Airco',
       'Automatic_airco', 'Boardcomputer', 'CD_Player', 'Central_Lock',
       'Powered_Windows', 'Power_Steering', 'Radio', 'Mistlamps',
       'Sport_Model', 'Backseat_Divider', 'Metallic_Rim', 'Radio_cassette',
       'Parking_Assistant', 'Tow_Bar', 'Diesel', 'Petrol', 'Black', 'Blue',
       'Green', 'Grey', 'Red', 'Silver', 'Violet', 'White', 'Yellow'],
      dtype='object')

In [9]:
table.to_excel('./data/ToyotaCorolla_cat2num.xls', sheet_name='data')

## Set Input and Output

In [10]:
table

Id                                              Model  Price  \
0        1      TOYOTA Corolla 2.0 D4D HATCHB TERRA 2/3-Doors  13500   
1        2      TOYOTA Corolla 2.0 D4D HATCHB TERRA 2/3-Doors  13750   
2        3      TOYOTA Corolla 2.0 D4D HATCHB TERRA 2/3-Doors  13950   
3        4      TOYOTA Corolla 2.0 D4D HATCHB TERRA 2/3-Doors  14950   
4        5        TOYOTA Corolla 2.0 D4D HATCHB SOL 2/3-Doors  13750   
5        6        TOYOTA Corolla 2.0 D4D HATCHB SOL 2/3-Doors  12950   
6        7      TOYOTA Corolla 2.0 D4D 90 3DR TERRA 2/3-Doors  16900   
7        8      TOYOTA Corolla 2.0 D4D 90 3DR TERRA 2/3-Doors  18600   
8        9        TOYOTA Corolla 1800 T SPORT VVT I 2/3-Doors  21500   
9       10        TOYOTA Corolla 1.9 D HATCHB TERRA 2/3-Doors  12950   
10      11  TOYOTA Corolla 1.8 VVTL-i T-Sport 3-Drs 2/3-Doors  20950   
11      12  TOYOTA Corolla 1.8 16V VVTLI 3DR T SPORT BNS 2...  19950   
12      13  TOYOTA Corolla 1.8 16V VVTLI 3DR T SPORT 2/3-D...  19600   
13      14  TOYOTA Corolla 1.8 16V VVTLI 3DR T SPORT 2/3-D...  21500   
14      15  TOYOTA Corolla 1.8 16V VVTLI 3DR T SPORT 2/3-D...  22500   
15      16  TOYOTA Corolla 1.8 16V VVTLI 3DR T SPORT 2/3-D...  22000   
16      17   TOYOTA Corolla 1.8 16V VVTLI 3DR T SPORT 2/3-...  22750   
17      18   TOYOTA Corolla 1.6 VVTI Linea Terra Comfort 2...  17950   
18      19             TOYOTA Corolla 1.6 16v L.SOL 2/3-Doors  16750   
19      20   TOYOTA Corolla 1.6 16V VVT I 3DR TERRA 2/3-Doors  16950   
20      21   TOYOTA Corolla 1.6 16V VVT I 3DR TERRA 2/3-Doors  15950   
21      22  TOYOTA Corolla 1.6 16V VVT I 3DR SOL AUT4 2/3-...  16950   
22      23     TOYOTA Corolla 1.6 16V VVT I 3DR SOL 2/3-Doors  15950   
23      24     TOYOTA Corolla 1.6 16V VVT I 3DR SOL 2/3-Doors  16950   
24      25     TOYOTA Corolla 1.6 16V VVT I 3DR SOL 2/3-Doors  16250   
25      26     TOYOTA Corolla 1.6 16V VVT I 3DR SOL 2/3-Doors  15950   
26      27     TOYOTA Corolla 1.6 16V VVT I 3DR SOL 2/3-Doors  17495   
27      28     TOYOTA Corolla 1.6 16V VVT I 3DR SOL 2/3-Doors  15750   
28      29     TOYOTA Corolla 1.6 16V VVT I 3DR SOL 2/3-Doors  16950   
29      30     TOYOTA Corolla 1.6 16V VVT I 3DR SOL 2/3-Doors  17950   
...    ...                                                ...    ...   
1406  1413  TOYOTA Corolla 1.6 16V HATCHB LINEA TERRA 2/3-...   8950   
1407  1414                 TOYOTA Corolla 1.6 GL LB 4/5-Doors   8250   
1408  1415       TOYOTA Corolla 1.6 16V HATCHB GTSI 2/3-Doors   9250   
1409  1416  TOYOTA Corolla 1.6 16V LIFTB LINEA TERRA 4/5-D...   7900   
1410  1417  TOYOTA Corolla 1.3 16V SEDAN LINEA TERRA 4/5-D...   8500   
1411  1418  TOYOTA Corolla 1.6 16V LIFTB LINEA TERRA 4/5-D...   7950   
1412  1419  TOYOTA Corolla 1.6 16V HATCHB LINEA TERRA 2/3-...   9950   
1413  1420  TOYOTA Corolla 1.6 16V LIFTB LINEA TERRA AUT4 ...   8750   
1414  1421  TOYOTA Corolla 1.6 16V HATCHB LINEA TERRA 2/3-...   7500   
1415  1422  TOYOTA Corolla 1.6 16V HATCHB LINEA TERRA 2/3-...   6950   
1416  1423                    TOYOTA Corolla 1.6 LB 4/5-Doors   8950   
1417  1424  TOYOTA Corolla 1.6 16V HATCHB LINEA TERRA AUT4...   8750   
1418  1425  TOYOTA Corolla 1.3 16V HATCHB LINEA TERRA 2/3-...   7750   
1419  1426  TOYOTA Corolla 1.6 16V HATCHB LINEA TERRA 2/3-...   8450   
1420  1427   TOYOTA Corolla 1.6 SDN LINEA TERRA AUT 4/5-Doors   8150   
1421  1428  TOYOTA Corolla 1.3 16V HATCHB LINEA TERRA AUT3...   8500   
1422  1429  TOYOTA Corolla 1.6 16V HATCHB LINEA TERRA 2/3-...   7600   
1423  1430    TOYOTA Corolla 1.3 HB LINEA TERRA AUT 2/3-Doors   7950   
1424  1431        TOYOTA Corolla 1.3 3D Linea Terra 2/3-Doors   7750   
1425  1432     TOYOTA Corolla 1.3 Linea Terra sedan 4/5-Doors   7950   
1426  1433        TOYOTA Corolla 1.6 Lin.Terra Aut. 2/3-Doors   9950   
1427  1434  TOYOTA Corolla 1.3 16V HATCHB LINEA TERRA AUT3...   8950   
1428  1435  TOYOTA Corolla 1.3 16V HATCHB LINEA TERRA 2/3-...   8450   
1429  1436           TOYOTA Corolla 1.3 Linea Te

In [11]:
X = table[['Age_08_04', 'Mfg_Month', 'Mfg_Year', 'KM',
       'HP', 'Met_Color', 'Automatic', 'CC', 'Doors', 'Cylinders', 'Gears',
       'Quarterly_Tax', 'Weight', 'Mfr_Guarantee', 'BOVAG_Guarantee',
       'Guarantee_Period', 'ABS', 'Airbag_1', 'Airbag_2', 'Airco',
       'Automatic_airco', 'Boardcomputer', 'CD_Player', 'Central_Lock',
       'Powered_Windows', 'Power_Steering', 'Radio', 'Mistlamps',
       'Sport_Model', 'Backseat_Divider', 'Metallic_Rim', 'Radio_cassette',
       'Parking_Assistant', 'Tow_Bar', 'Diesel', 'Petrol', 'Silver',
       'Violet', 'Grey', 'Yellow', 'Blue', 'Green', 'Red', 'Black',
       'White']]
y = table['Price']

X = X.as_matrix()
y = y.as_matrix()

In [12]:
X.shape, y.shape

((1436, 45), (1436,))

In [13]:
len(X)

1436

In [14]:
import numpy as np

np.random.seed(123)

#Shuffle data
permutation = np.random.permutation(len(X))
X = X[permutation]
y = y[permutation]

# Split data
N_train = int(len(X) * 4 / 5)

X_train = X[:N_train]
y_train = y[:N_train]

X_test = X[N_train:]
y_test = y[N_train:]

# Linear Regression Using Scikit-Learn

In [15]:
from sklearn import linear_model

model = linear_model.LinearRegression()
model.fit(X_train,y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [16]:
model.coef_

array([-1.11548091e+02, -8.37376980e+01,  1.62738158e+01, -1.74948928e-02,
        1.50405283e+01, -5.59544124e+01,  3.54783866e+02, -8.32101083e-02,
        5.20610957e+01,  8.52651283e-13,  1.96586752e+02,  1.23349629e+01,
        1.03420775e+01,  2.50303124e+02,  5.04947452e+02,  6.18167088e+01,
       -2.19455195e+02,  3.32716105e+01, -6.92014118e+01,  2.63898425e+02,
        2.63218273e+03, -1.57350162e+02,  2.55785228e+02, -9.98479238e+01,
        3.59173001e+02,  2.61894500e+02,  4.90484621e+02, -1.36437337e+02,
        2.98123049e+02, -2.88792660e+02,  2.97363961e+02, -5.60527137e+02,
       -1.18595182e+03, -1.40867398e+02,  1.08736942e+03,  1.90256373e+03,
        6.35973417e+02,  2.66773243e+02,  7.85960205e+02,  6.13952474e+02,
        5.77502698e+02,  3.71745725e+02,  4.17557394e+02,  6.85824055e+02,
       -3.90456361e+02])

## Evaluation

In [17]:
y_train_hat = model.predict(X_train)
y_test_hat = model.predict(X_test)

In [18]:
print(np.round(y_train[:10]))
print(np.round(y_train_hat[:10]))

[12950 16500  9900  7950 15950  7995  9950  8450  7950 16750]
[12440. 17934. 10351.  8885. 15482.  9871.  8443.  7041.  6998. 16484.]


In [19]:
print(np.round(y_test[:10]))
print(np.round(y_test_hat[:10]))

[ 8450  7145  8950  8450 12500  9950 10950  5950  8950  9930]
[ 7422.  7783.  9735.  8369. 10279. 10830. 11907.  7489.  8172. 10747.]


In [20]:
from sklearn import metrics

print("Train r^2: ", metrics.r2_score(y_train, y_train_hat))
print("Test r^2: ", metrics.r2_score(y_test, y_test_hat))

Train r^2:  0.9137657919415272
Test r^2:  0.8912397293089547


# Regularization

In [21]:
from sklearn import linear_model

lm = linear_model.Lasso(alpha=0.1, max_iter=10000)
model = lm.fit(X_train,y_train)

In [22]:
y_train_hat = model.predict(X_train)
y_test_hat = model.predict(X_test)

In [23]:
from sklearn import metrics

print("Train r^2: ", metrics.r2_score(y_train, y_train_hat))
print("Test r^2: ", metrics.r2_score(y_test, y_test_hat))

Train r^2:  0.9137507321317346
Test r^2:  0.8914394794721457
